# Generated by Django 4.2.5 on 2023-11-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_interface', '0002_alter_auxiliarymaterials_time_1st_weighing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxiliarymaterials',
            name='Surplus',
        ),
    ]
