# Generated by Django 4.2.5 on 2023-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_interface', '0004_alter_auxiliarymaterials_lack_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logshippedproducts',
            name='Gross_weight_kilos',
            field=models.FloatField(default=38956),
            preserve_default=False,
        ),
    ]
