# Generated by Django 4.2.5 on 2023-11-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_interface', '0005_logshippedproducts_gross_weight_kilos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logshippedproducts',
            name='Gross_weight_kilos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
